config/routes.rb
Devilray::Application.routes.draw do
  resources :manta_accounts
  resources :manta_files, only: [:index]
  devise_for :users

  root 'welcome#index'

  

end

app/models/manta_account.rb
class MantaAccount < ActiveRecord::Base
  belongs_to :user
  before_save :set_active
  validates :manta_username, presence: true
  validates :manta_host, presence: true
  validates :manta_private_key, presence: true

  def set_active
    if self.active == true || self.user.manta_accounts.any? {|acct| !acct.active? }
      active = true
      self.user.manta_accounts.where("id != ?", self.id).update_all(active: false)
    end
  end
end

app/models/manta_dir.rb
class MantaDir < MantaObj

  def list_directory
    contents = manta_client.list_directory(self.full_path)[0]
    contents.collect! do |content|
      content["full_path"] = self.full_path + "/#{content["name"]}"
      if content["type"] == "object"
        content = MantaFile.new(content.merge!(user_id: self.user_id))
      elsif content["type"] == "directory"
        content = MantaDir.new(content.merge!(user_id: self.user_id))
      end
    end
    contents
  end

end

app/models/manta_file.rb
class MantaFile < MantaObj

  def file_data
    file_data, headers = manta_client.get_object(full_path)
    file_data
  end

  def delete
    file_status, headers = manta_client.delete_object(full_path)
    file_status
  end
  
  def signed_url(valid_for)
    "https://#{manta_client.gen_signed_url(Time.now + valid_for, :get, full_path)}"
  end

end

app/models/manta_obj.rb
class MantaObj
  include ActiveModel::Model
  attr_accessor :name, :etag, :size, :type, :mtime, :full_path, :user_id


  def user=(user)
    self.user_id = user.id
  end

  def user
    User.find(self.user_id)
  end

  def manta_client
    client = MantaClient.new(user.active_manta_account.manta_host,
                             user.active_manta_account.manta_username,
                             user.active_manta_account.manta_private_key)
  end

  def persisted?
    true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :manta_accounts
  has_one :active_manta_account, -> { where active: true }, class_name: "MantaAccount"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def setup?
    manta_accounts.any? {|acct| acct.manta_username.present? &&
                          acct.manta_host.present? &&
                          acct.manta_private_key.present?}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_manta_account

  def current_manta_account
    if current_user && current_user.manta_accounts.any? {|acct| acct.active?}
      current_user.manta_accounts.where(active: true).first
    end
  end
end

app/controllers/manta_accounts_controller.rb
class MantaAccountsController < ApplicationController
  before_filter :set_manta_account, except: [:index, :new, :create]
  before_filter :authenticate_user!
  def index
    @manta_accounts = current_user.manta_accounts
  end

  def show
  end

  def new
    @manta_account = current_user.manta_accounts.new
  end

  def create
    @manta_account = current_user.manta_accounts.new(new_manta_account_params)
    if @manta_account.save
      redirect_to manta_account_url(@manta_account)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @manta_account.update_attributes(update_manta_account_params)
      redirect_to manta_account_url(@manta_account), notice: "Account Updated!"
    else
      render :edit
    end
  end

  def destroy
    @manta_account.destroy
    redirect_to manta_accounts_url
  end

  private

  def new_manta_account_params
    params.require(:manta_account).permit(:manta_username, :manta_host, :manta_private_key, :active)
  end

  def update_manta_account_params
    params.require(:manta_account).permit(:manta_username, :manta_host, :active)
  end

  def set_manta_account
    @manta_account = current_user.manta_accounts.find(params[:id])
  end
end

app/controllers/manta_files_controller.rb
class MantaFilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_manta_dir, only: [:index]

  def index
    @manta_files = @manta_dir.list_directory
  end

  private

   def set_manta_dir
    path = params[:manta_path] || "/#{current_manta_account.manta_username}/stor"
    @manta_dir = MantaDir.new(full_path: path, user: current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manta_accounts_helper.rb
module MantaAccountsHelper
end

app/helpers/manta_files_helper.rb
module MantaFilesHelper
  def file_icon(file_obj)
    if file_obj.is_a?(MantaDir)
      "folder outline"
    elsif file_obj.is_a?(MantaFile)
      "file outline"
    end
  end
  def manta_breadcrumbs(full_path)
    root = "/#{current_manta_account.manta_username}/stor"
    if full_path == root
      link_to root, manta_files_path, class: 'active section'
    else
      crumbs = ''
      crumbs << "#{link_to root, manta_files_path, class: 'section'}"
      remaining_path = full_path.gsub(root, '')
      remaining_path.split("/")[1..-1].each_with_index do |dir, i|
        crumbs << "<div class='divider'> / </div>"
        dir_target_path = manta_files_path(path: root + remaining_path.split('/')[0..i+1].join("/"))
        crumbs << "#{link_to dir, dir_target_path, class: ('section active' if remaining_path.split("/")[-1] == dir ) }"
      end
      crumbs.html_safe
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Devilray
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = render "shared/navbar"
    = semantic_flash

    = yield

app/views/manta_accounts/_form.html.slim
.ui.segment.form
  = simple_form_for(@manta_account) do |f|
    = f.input :manta_username
    = f.input :manta_host
    = f.input :manta_private_key
    - if @manta_account.user.manta_accounts.present?
      = f.input :active
    = f.submit

app/views/manta_accounts/_manta_account.html.slim
tr
  td= link_to manta_account.manta_username, edit_manta_account_path(manta_account)
  td= manta_account.manta_host
  td= manta_account.manta_private_key.present? ? "Yes" : "No"
  td= manta_account.active?

app/views/manta_accounts/edit.html.slim
h1 Editing #{@manta_account.manta_username}
i Private Keys can only be set when you setup your Manta account for the first time.
.ui.segment.form
  = simple_form_for(@manta_account) do |f|
    = f.input :manta_username
    = f.input :manta_host
    - if @manta_account.user.manta_accounts.present?
      = f.input :active
    .ui.buttons
      = f.submit "Update", class: "ui button blue"
      = link_to "Delete", manta_account_path(@manta_account), class: "ui button red", method: :delete, data: {confirm: "Delete this account?"}

app/views/manta_accounts/index.html.slim
h1 Your Manta Accounts

- if @manta_accounts.empty?
  h3 You Don't have any Manta Accounts. #{link_to "Create One?", new_manta_account_path}
- else
  table.ui.table.segment
    thead
      tr
        th Username
        th API Endpoint
        th Key Present?
        th Active
    tbody
      = render @manta_accounts
    tfoot
      tr
        th colspan="4"
          = link_to new_manta_account_path, class: "ui button blue small" do
            = semantic_icon("user")
            | New

app/views/manta_accounts/new.html.slim
h1 Create A Manta Account

= render "form"

app/views/manta_accounts/show.html.slim
h1 Manta Account

table.ui.table.segment
  tbody
    tr
      th Username
      td= @manta_account.manta_username
    tr
      th API Endpoint
      td= @manta_account.manta_host
    tr
      th Private Key Present
      td= @manta_account.manta_private_key.present? ? "Yes" : "No"
    tr
      th Active Now?
      td= @manta_account.active? ? "Yes" : "No"

= link_to "Back to Account List", manta_accounts_path

app/views/manta_dirs/_manta_dir.html.slim
tr
  td= semantic_icon(file_icon(manta_dir))
  td= link_to manta_dir.name, manta_files_path(manta_path: manta_dir.full_path)
  td
  td= manta_dir.mtime
  td

app/views/manta_files/_manta_file.html.slim
tr
  td= semantic_icon(file_icon(manta_file))
  td= link_to manta_file.name, manta_file.signed_url(24.hours)
  td= number_to_human_size(manta_file.size)
  td= manta_file.mtime
  td

app/views/manta_files/index.html.slim
.ui.segment.crumbbox
  .ui.breadcrumb
    = manta_breadcrumbs(@manta_dir.full_path)
table.ui.table.segment
  thead
    tr
      th
      th Filename
      th Size
      th Mtime
      th Actions
  tbody
    = render @manta_files

app/views/shared/_navbar.html.slim
.ui.menu.inverted
  = link_to "DevilRay", root_path, class: 'item'
  - if current_user && current_user.setup?
    = link_to manta_files_path, class: 'item' do
      = semantic_icon('file icon')
      span Files
    = link_to "#", class: 'item' do
      = semantic_icon("tasks")
      span Jobs
    = link_to "#", class: 'item' do
      = semantic_icon("dashboard")
      span Reports
  .right.menu
    - if current_user
      - if current_manta_account
        = link_to manta_accounts_path, class: 'item' do
          = semantic_icon('cloud')
          = current_manta_account.manta_username
      - else
        = link_to "Manta Accounts", manta_accounts_path, class: 'item'
      = link_to "Edit Profile", edit_user_registration_path, class: 'item'
      = link_to "Log Out", destroy_user_session_path, class: 'item', method: :delete
    - else
      = link_to "Sign In", new_user_session_path, class: 'item'

app/views/welcome/index.html.slim
.ui.segment.hero
  h1 Welcome to DevilRay, the Manta Explorer.
  - if current_user && !current_user.setup?
    h3 You don't have any Manta Accounts. You should probably #{link_to 'Create One', new_manta_account_path}.
  - elsif current_user && current_user.setup?
    h3 You're looking good today.
  - else
    h3 #{link_to "Sign In", new_user_session_path} or #{link_to "Sign Up", new_user_registration_path} to browse your Manta data.
    h3 Don't have a Joyent Account yet?
    h3 Set one up here: #{link_to "Joyent Sign-up", "https://sso.joyentcloud.com/signup"} then get started back here!